<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@100;200;300;400;500;600;700;800&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="assets/css/style.css">
		<title>Exercice Routeur MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="./">Accueil</a>
					</li>
					<li>
						<a href="nos-tarifs">Tarifs</a>
					</li>
				</ul>
                <hr>
			</nav>
		</header>
	</body>
</html>