
<main>
    <section class="bandeau">
        <div claas="bandeauDiv">
            <!-- <img class="fond" src="./assets/images/cemetery.jpeg" alt="fond cimetière"> -->
            <div class="logo">
                <img src="./assets/images/<?= $data['logo'] ?>" alt="logo">
                <h1><?= $data['name'] ?></h1>
            </div>
            <h3><?= $data['tagline'] ?></h3>
        </div>
    </section>
</main>
