<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Dilemme pas connu du tout</title>
        <link rel="stylesheet" href="assets/styles/style.css">
    </head>
    <body>
        <?php require "templates/partials/_header.phtml"?>
        <?php require "templates/partials/_main.phtml"?>
        <?php require "templates/partials/_footer.phtml"?>
    </body>
</html>