<main class="container py-5">
    <?php require "controllers/get-user.php" ?>
    <a href="index.php?route=list">Retour à la liste</a>
    <h1 class="my-5">Modifier un utilisateur</h1>
    <?php if (isset($user) && is_array($user)): ?>
    <form method="post" action="controllers/update-user.php">
        <fieldset class="form-group mb-2">
            <label class="form-label" for="user-id">Id</label>
            <input class="form-control" type="text" name="user-id" id="user-id" value=<?= $user['id'] ?> readonly required>
        </fieldset>
        <fieldset class="form-group mb-2">
            <label class="form-label" for="name">Nom</label>
            <input class="form-control" type="text" name="name" id="name" value=<?= $user['username'] ?> required>
        </fieldset>
        <fieldset class="form-group mb-2">
            <label class="form-label" for="email">Email</label>
            <input class="form-control" type="email" name="email" id="email" value=<?= $user['email'] ?> required>
        </fieldset>
        <fieldset class="form-group mb-5">
            <label class="form-label" for="job">Emploi</label>
            <select class="form-select" id="job" name="job">
                <option value="">Sélectionnez l'emploi</option>
                <option value="1" <?php if ($user['job'] == 1) echo 'selected'; ?>>Journaliste</option>
                <option value="2" <?php if ($user['job'] == 2) echo 'selected'; ?>>Conservatrice de musée</option>
                <option value="3" <?php if ($user['job'] == 3) echo 'selected'; ?>>Riche</option>
                <option value="4" <?php if ($user['job'] == 4) echo 'selected'; ?>>Vétéran</option>
                <option value="5" <?php if ($user['job'] == 5) echo 'selected'; ?>>Lycéen</option>
            </select>
        </fieldset>
        <fieldset class="form-group">
            <button class="btn btn-primary" type="submit">Enregistrer</button>
        </fieldset>
        <?php else: ?>
    <p>Erreur : données utilisateur non disponibles.</p>
<?php endif; ?>
    </form>
</main>